import { isValidUsername } from "@/lib/sanitize";

const ADJECTIVES = [
  "brave",
  "bold",
  "bright",
  "calm",
  "clever",
  "cosmic",
  "curious",
  "eager",
  "fearless",
  "free",
  "gentle",
  "golden",
  "happy",
  "hearty",
  "humble",
  "jolly",
  "keen",
  "kind",
  "lively",
  "lucky",
  "mellow",
  "merry",
  "noble",
  "playful",
  "proud",
  "quick",
  "radiant",
  "salty",
  "serene",
  "shiny",
  "spirited",
  "steady",
  "sunny",
  "swift",
  "true",
  "vivid",
  "wander",
  "warm",
  "wise",
  "young",
  "zesty",
] as const;

const NOUNS = [
  "trekker",
  "traveler",
  "voyager",
  "explorer",
  "hiker",
  "nomad",
  "pilgrim",
  "ranger",
  "scout",
  "sailor",
  "pilot",
  "dreamer",
  "rover",
  "walker",
  "climber",
  "discoverer",
  "wanderer",
  "backpacker",
  "adventurer",
  "trailblazer",
  "wayfarer",
  "camper",
  "stargazer",
  "sunrise",
  "sunset",
  "horizon",
  "canyon",
  "glacier",
  "meadow",
  "summit",
  "valley",
  "forest",
  "desert",
  "island",
  "ocean",
  "river",
  "mountain",
  "coast",
  "peak",
  "ridge",
  "trail",
  "dune",
  "grove",
  "harbor",
  "lagoon",
  "plateau",
  "prairie",
  "reef",
  "savanna",
  "tundra",
  "waterfall",
] as const;

function randomItem<T>(list: readonly T[], random: () => number): T {
  return list[Math.floor(random() * list.length)];
}

export function generateUsername(random: () => number = Math.random): string {
  for (let attempt = 0; attempt < 100; attempt += 1) {
    const candidate = `${randomItem(ADJECTIVES, random)}.${randomItem(NOUNS, random)}`;
    if (isValidUsername(candidate)) return candidate;
  }
  return `traveler${Math.floor(random() * 1_000_000)}`;
}
