// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const databaseUrl = env("DATABASE_URL");
const migrationDatabaseUrl = process.env.MIGRATION_DATABASE_URL;

if (migrationDatabaseUrl) {
  const migrationHost = new URL(migrationDatabaseUrl).hostname;
  const databaseHost = new URL(databaseUrl).hostname;
  const isLocalhost = (host: string) =>
    host === "localhost" || host === "127.0.0.1" || host === "::1";
  const isSupabaseHost = (host: string) =>
    host.endsWith(".supabase.co") || host.endsWith(".supabase.com");
  const mixesLocalAndSupabase =
    (isLocalhost(migrationHost) && isSupabaseHost(databaseHost)) ||
    (isSupabaseHost(migrationHost) && isLocalhost(databaseHost));

  if (mixesLocalAndSupabase) {
    throw new Error(
      `Refusing to mix local and Supabase databases: MIGRATION_DATABASE_URL (${migrationHost}), DATABASE_URL (${databaseHost}).`,
    );
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed-dummy-data.ts",
  },
  datasource: {
    url: migrationDatabaseUrl || databaseUrl,
  },
});
