// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed-dummy-data.ts",
  },
  datasource: {
    // Migrations must connect directly rather than through the runtime pooler.
    // In development, CLI commands (db push, migrate dev, etc.) target the
    // local database (prisma dev) instead of the production migration URL.
    url:
      process.env.NODE_ENV === "production"
        ? env("MIGRATION_DATABASE_URL")
        : env("DATABASE_URL"),
  },
});
