// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed-dummy-data.ts",
  },
  datasource: {
    // Migrations must connect directly rather than through the runtime pooler.
    url: env("MIGRATION_DATABASE_URL"),
  },
});
